# config/assets.yml
js:
  base:
    - jquery-1.7.1.min.js
    - jquery.easing.1.3.js
    - jquery.form.js
    - cufon/cufon-yui.js
    - cufon/*.font.js
    - jquery-ui-1.8.16.custom/js/*.js
    - booklet/*.booklet.*.js
    - app.js
    - booklet.js
    - links.js
    
css:
  base:
    - ../javascripts/jquery-ui-1.8.16.custom/css/blue-green-ct/*.css
    - ../javascripts/booklet/*.css
    - style.css
    - links.css
    - booklet.css